title: the blog of champions
author: Bridger Harris
email: blharris@students.uinta4.com
description: this is the blog of champions. we aresports addicts and stuff. trump2020

# social links
twitter_username: dont have one
github_username:  BridgerHarris

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
